In [2]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [4]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [5]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [6]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) } # ch is character and i is index/integer, string to index
itos = { i:ch for i,ch in enumerate(chars) } # same, index to string 
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [7]:
import torch # we use PyTorch: https://pytorch.org
#data tensor
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [8]:
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [9]:
#Max length of the data along which we will train our transformers with
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [10]:
x = train_data[:block_size] #inputs to the transformer
#prediciting the next character here as like what happens in GPT 2 architechure.
y = train_data[1:block_size+1] #target for each position in the input as we want to predict the next position according to the prev. position
for t in range(block_size):
    context = x[:t+1] #all characters upto t including t
    target = y[t] # next character that we will predict using the current characters.
    print(f"when input is {context} the target: {target}") #output is the 8 characters hidden in the chunk of 9 characters we sampled from the training set 

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [11]:
#Batches of multiple chunks of text feeded into the transformer, all stacked up in the single tensor, for efficiency to keep the GPUs busy
#due to parallel processing of data, chunks feeded properly and these chunks didn't talk to each other

torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel in forward and backward pass of transformer
block_size = 8 # what is the maximum context length for predictions for 1 independent source

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) #batch_size number of random offsets,4
    x = torch.stack([data[i:i+block_size] for i in ix]) #stacking together the data in rows in 4*8 matrix
    y = torch.stack([data[i+1:i+block_size+1] for i in ix]) #this is just as the above block here we are just adding +1 in elements
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53

In [12]:
print(xb) # our input to the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [14]:
#Here, we are using the bi-gram model in which we are feeding the whole text to the model but to predict the next character we only use the last
#character but in general in the real life we need the previous whole context to predict the next characterz
#using the baseline model

import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module): #from nn.module we are importing bigram language model 

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)#The index will pluck out the whole row from the embedding table according
        #to the defined index, idx, e.g. in above case 24 will go and pluck out the 24th row from the embedding table and so on.

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C) (pytorch arrange the tensor into batch by time by channel tensor)
        #batch = 4, time = 8, channel = vocab_Size = 65
        #logits are the scores for the next character in the sequence, predicitng what comes next just by the individual identity of single token
        # because here tokens are not talking to each other and every token is an individual token and they are not seeing any context

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape #changing the dimensions according to our need
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets) #cross entropy is same as negative log likelihood
            #to understand or find the loss, how well we are prediciting the next character
            #according to logits
        #cross_entropy wants the dimensions to be B,C,T instead of B,T,C
        #logits give us the next character that we are predicting and targets are the one's which we have in our dataset already defined
        #intial loss would be  = -ln(1/65) as the vocab size is 65 and each character has the predicition prob to occur will be equally likely
        #loss tells how well are our logits according to our targets.
        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context, we need to take B,T and generate the next index
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx) #self(idx) will go to the forward pass from here
            # focus only on the last time step, to predict the next one
            logits = logits[:, -1, :] # becomes (B, C), using only the last character to predict the next character
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C), -1 means softmax must be applied to the last dimension of the input tensor
            # sample from the distribution, to predict one next character
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence, what we predicted is concatenated to the next dimension
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [15]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True) #zeroing gradients from the previous steps/ # Zero the gradients (to avoid accumulation from multiple passes)
    loss.backward() # backprop/ to calculate the gradient of the tensor
    optimizer.step() # update the weights

print(loss.item())

2.44732928276062


In [20]:

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=400)[0].tolist()))


Whocasll ith, I oow iloure:
Angowornon!'d ll aleroumeatt gin ETovee'd
AUSO Fodin PAY:
I p s!
Piven ris cker er, s o coveceenobur an:

POKisteth t, is? the thee.
dit s are;
Witheane; te faveapeveeveig ar: anose ay ofosesenk t mendst LBover, whlos
K:
Ker, y, w noue, s:-us he my'Cang.
Thingad ththtrd, ad it ts bl lo bt ph he w.
S:
MNUCAs, r tid ber s amyot therd atho pesf' thevecivatourattee poun tep
